context:
  version: "2.76.4"
  major_minor: "2.76"

package:
  name: glib
  version: ${{ version }}

source:
  url: https://download.gnome.org/sources/glib/${{ major_minor }}/glib-${{ version }}.tar.xz
  sha256: 5a5a191c96836e166a7771f7ea6ca2b0069c603c7da3cba1cd38d1694a395dda
  patches:
  - patches/00_skip_res_query_test.patch
  - patches/01_fix_function_type.patch
  - patches/02_fix_gpointer_fun_types.patch
    # patches taken from webR
    # License: MIT
    # - patches/emscripten-configure.diff
    # - patches/emscripten-function-ptr.diff
    # - patches/emscripten-wasm.diff
    # - patches/emscripten-disable-pcre.diff
    # - patches/fix-python12.diff

build:
  number: 0

requirements:
  build:
    - pkg-config
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - ninja
    - meson
  host:
    - zlib
    - libffi
    - pcre2>=10.43

about:
  homepage: https://developer.gnome.org/glib/
  license: LGPL-2.1-or-later
  summary: Provides core application building blocks for libraries and applications written in C.
