context:
  name: r-plotly
  version: 4.10.4
  r_base_version: 4.4.2

source:
  url:
    - https://cran.r-project.org/src/contrib/${{ name[2:] }}_${{ version }}.tar.gz
    - https://cloud.r-project.org/src/contrib/${{ name[2:] }}_${{ version }}.tar.gz
  sha256: cfa995b7ed55d31a196707a3ae6ea352dd907cef3058a3bf1956fde39366d867

build:
  number: 0
  script: $R CMD INSTALL $R_ARGS --no-byte-compile .

outputs:
- package:
    name: ${{ name }}
    version: ${{ version }}
  build:
    files:
      - lib/R/library/${{ name[2:] }}/*
  requirements:
    build:
      - cross-r-base >= ${{ r_base_version }}
      - ${{ compiler('c') }}
      - ${{ compiler('cxx') }}
    host:
      - r-base >= ${{ r_base_version }}
      - r-base64enc
      - r-crosstalk
      - r-data.table
      - r-digest
      - r-dplyr
      - r-htmltools
      - r-htmlwidgets==1.6.4
      - r-rmarkdown>=2.29
      - r-bslib>=0.8
      - r-jsonlite
      - r-lazyeval
      - r-magrittr
      - r-promises
      - r-purrr
      - r-rcolorbrewer
      - r-tibble
      - r-tidyr
      - r-vctrs
      - r-viridisLite
    run:
      - r-base >= ${{ r_base_version }}
      - r-base64enc
      - r-crosstalk
      - r-data.table
      - r-digest
      - r-dplyr
      - r-htmltools
      - r-htmlwidgets
      - r-jsonlite
      - r-lazyeval
      - r-magrittr
      - r-promises
      - r-purrr
      - r-rcolorbrewer
      - r-tibble
      - r-tidyr
      - r-vctrs
      - r-viridisLite

  tests:
  - package_contents:
      lib:
      - R/library/${{ name[2:] }}/libs/${{ name[2:] }}.so

about:
  homepage: https://plotly-r.com
  repository: https://github.com/ropensci/plotly
  license: MIT
  license_file: LICENSE
  summary: An interactive graphing library for R
  description: |
    Create interactive web graphics from 'ggplot2' graphs and/or a custom
    interface to the (MIT-licensed) JavaScript library 'plotly.js' inspired by
    the grammar of graphics.

extra:
  recipe-maintainers:
  - IsabelParedes
