context:
  name: matplotlib
  version: 3.10.2

source:
- url: https://github.com/matplotlib/matplotlib/archive/v${{ version }}.tar.gz
  sha256: dadf06cd532b7fcc21696aebd6016e565844cc97961be05d80ce59d2264c93af
  patches:
  - patches/fix-threading-and-font-cache.patch
  - patches/static-cast.patch

build:
  number: 0

outputs:
- package:
    name: matplotlib-base
    version: ${{ version }}
  build:
    script: build-base.sh
  requirements:
    build:
    - python
    - pip
    - cross-python_${{ target_platform }}

    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - pkg-config
    - meson-python
    - numpy
    - setuptools_scm_git_archive

      # to template the emscripten.meson.cross file
    - sed

    host:
    - python
    - numpy
    - pybind11
    - freetype
    - qhull
    run:
    - contourpy
    - cycler
    - fonttools
    - kiwisolver
    - numpy
    - packaging
    - pillow
    - pyparsing
    - python-dateutil
    - pytz

- package:
    name: matplotlib
    version: ${{ version }}

  requirements:
    host:
    - python
    run:
    - python
    - ${{ pin_subpackage('matplotlib-base', exact=True) }}

  tests:
  - script: pytester
    files:
      recipe:
      - test_import_matplotlib.py
    requirements:
      build:
      - pytester
      run:
      - pytester-run
