context:
  version: 3.2.0

package:
  name: xeus-lite
  version: ${{ version }}

source:
  url: https://github.com/jupyter-xeus/xeus-lite/archive/refs/tags/${{ version }}.tar.gz
  sha256: 7ec4c84ec83910f1827b062bb6e11ee7fee69b57a0935aba11fb8514f0570b70

build:
  number: 0

requirements:
  build:
  - ${{ compiler("cxx") }}
  - cmake
  - ninja
  host:
  - nlohmann_json
  - xeus >=5.0.0

about:
  license: BSD-3-Clause
  license_family: BSD-3
  license_file: LICENSE
  summary: xeus
  homepage: https://github.com/jupyter-xeus/xeus-lite
extra:
  recipe-maintainers:
  - DerThorsten
  - JohanMabille

