context:
  version: 4.0.0

package:
  name: xeus-lite
  version: ${{ version }}

source:
  url: https://github.com/jupyter-xeus/xeus-lite/archive/refs/tags/${{ version }}.tar.gz
  sha256: e64a509d2a2fae780bbcfb10d9c1713cd8c6e947ae012e3a244470b6e776380b

build:
  number: 0

requirements:
  build:
  - ${{ compiler("cxx") }}
  - cmake
  - ninja
  host:
  - nlohmann_json
  - xeus >=5.0.0

tests:
- script:
  - test -f $PREFIX/lib/libxeus-lite.a

about:
  license: BSD-3-Clause
  license_family: BSD-3
  license_file: LICENSE
  summary: xeus
  homepage: https://github.com/jupyter-xeus/xeus-lite
extra:
  recipe-maintainers:
  - DerThorsten
  - JohanMabille

