context:
  name: "lightgbm"
  version: "3.3.2"

package:
  name: "{{ name }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  # url: https://files.pythonhosted.org/packages/8f/51/d272fa065be3be615d279be915705fa3824b86155e36c974cfb8d3ceec1e/lightgbm-3.3.2.tar.gz
  sha256: 5d25d16e77c844c297ece2044df57651139bc3c8ad8c4108916374267ac68b64

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  build:
    - python                              # [build_platform != target_platform]
    - cross-python_emscripten-32
  host:
    - python
    - pip
  run:
    - numpy
    - scipy
    - scikit-learn

test:
  imports:
    - lightgbm

about:
  home: https://github.com/microsoft/LightGBM
  PyPI: https://pypi.org/project/lightgbm
  summary: LightGBM Python Package
  license: The MIT License (Microsoft)

extra:
  recipe-maintainers:
    - ihuicatl
