context:
  name: cross-python_emscripten-wasm32
  version: "3.12.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

build:
  number: 0

requirements:

  run:
    - coreutils
    - crossenv >=1.2
    - emscripten_emscripten-wasm32
    - rsync
    - sed
    - python 3.12
    - setuptools #<60.0
    - pip
    
about:
  summary: cross-python

extra:
  recipe-maintainers:
    - DerThorsten
