context:
  name: "readline"
  version: "8.2"

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://ftp.gnu.org/gnu/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: 3feb7171f16a84ee82ca18a36d7b9be109a52c04f492a053331d7d1095007c35

build:
  number: 0

requirements:
  build:
    - pkg-config
    - ${{ compiler('c') }}
    - make
    - libtool
  host:
    - ncurses
  run:
    - ncurses

# test:
#   commands:
#   {% set readline_libs = [
#     'libreadline',
#     'libhistory'
#   ] %}
#   {% for lib in readline_libs %}
#     - test ! -f ${PREFIX}/lib/{{ lib }}.a
#     - test -f ${PREFIX}/lib/{{ lib }}${SHLIB_EXT}  # [not win]
#   {% endfor %}

about:
  homepage: https://tiswww.cwru.edu/php/chet/readline/rltop.html
  license: GPL-3.0-only
  license_file: COPYING
  summary: Library for editing command lines as they are typed in.

extra:
  recipe-maintainers:
    - IsabelParedes
