context:
  name: git2cpp
  version: 0.0.2

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://github.com/QuantStack/${{ name }}/archive/refs/tags/${{ version }}.tar.gz
  sha256: a18bad851bbe5243aeeb3cfa048de25fbfcf881b363ab0b5e4f6252a8772041e

build:
  number: 0

requirements:
  build:
    - ${{ compiler("cxx") }}
    - cli11
    - meson
    - pkg-config
  host:
    - libgit2>=1.9.0

tests:
  - script:
    - test -f $PREFIX/bin/git2cpp.js
    - test -f $PREFIX/bin/git2cpp.wasm
  - script: |
      OUTPUT=$(run_modularized $PREFIX/bin/git2cpp.js --version | cut -c -15)
      if [[ "$OUTPUT" != "git2cpp version" ]]; then
        echo "Unexpected output: $OUTPUT"
        exit 1
      fi
    requirements:
      build:
        - run_modularized >= 0.1.2

about:
  homepage: https://github.com/QuantStack/git2cpp
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ianthomas23
