context:
  name: "cairo"
  version: 1.16.0

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: http://cairographics.org/releases/${{ name }}-${{ version }}.tar.xz
  sha256: 5e7b29b3f113ef870d1e3ecf8adf21f923396401604bda16d44be45e66052331

build:
  number: 0

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - meson
    - ninja
    - pkg-config
    - freetype
  host:
    - freetype
    - fontconfig
    - glib
    - libpng
    - pixman
    - lzo
    - expat

tests:
- script:
    - test -f $PREFIX/lib/libcairo.a
    - test -f $PREFIX/lib/libcairo-gobject.a
    - test -f $PREFIX/include/cairo/cairo.h

about:
  homepage: http://cairographics.org/
  documentation: https://www.cairographics.org/documentation/
  license: MPL-1.1 # or LGPL-2.1-only
  license_file:
    - COPYING
    - COPYING-LGPL-2.1
    - COPYING-MPL-1.1
  summary: |
    Cairo is a 2D graphics library with support for multiple output devices.

extra:
  recipe-maintainers:
    - IsabelParedes