context:
  name: octave
  version: 10.2.0

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url:
  - https://ftp.gnu.org/gnu/${{ name }}/${{ name }}-${{ version }}.tar.gz
  - https://ftpmirror.gnu.org/${{ name }}/${{ name }}-{{ version }}.tar.gz
  sha256: 07fb6d9339d2f350735c91671be8e874d16- 0018cc6b688f9efd9d558d237f69f
  patches:
  - 0001-Add-emscripten-platform-support.patch
  - 0002-Fix-weird-nesting.patch
  - 0003-Disable-threads.patch
  - 0004-Custom-link-octave-cli.patch
  - 0005-Remove-rpath.patch
  - 0006-Assume-little-endian.patch
  - 0007-MAYBE-Set-SIDE_MODULE-to-1.patch
  - 0008-Set-octave-cli-flags.patch
  - 0009-Fix-Fortran-calling-convention.patch
  - 0010-Remove-redundant-headers.patch
  - 0011-Fix-duplicate-convert_enum-error.patch
  - 0012-Return-void-from-xerbla.patch
  - 0013-Add-emscripten-mutex.patch
  - 0014-Disable-path-modifications.patch
  - 0015-Disable-multithreading.patch
  - 0016-Disable-gui-calls-and-threading.patch
  - 0017-Adapt-signal-wrappers.patch
  - 0018-FIXME-abort-calls-native-code-failure.patch

build:
  number: 0

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    # - micromamba  # flang activation script
    # - flang_${{ target_platform }}
    # Cannot upload custom llvm to prefix-dev
    # - llvm_${{ target_platform }} >= 20.1
    - make
    - libtool>=2.5.4
    - pkg-config
    - grep
    - sed
    - perl
    - ghostscript
    - bison
    - gperf
  host:
    - libflang
    # - openblas-flang  # libblas, libcblas, liblapack
    - libblas
    - liblapack
    - pcre2>=10.43
    - freetype
  run_exports:
    - ${{ pin_subpackage('octave', upper_bound='x') }}

about:
  homepage: https://www.gnu.org/software/octave/
  license: GPL-3.0-or-later
  license_file: COPYING
  documentation: https://www.gnu.org/software/octave/doc/interpreter/
  summary: GNU Octave is a high-level language, primarily intended for numerical computations
