context:
  name: scipy-flang
  version: 1.15.2

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  - url: https://pypi.org/packages/source/s/scipy/scipy-${{ version }}.tar.gz
    sha256: cd58a314d92838f7e6f755c8a2167ead4f27e1fd5c1251fd54289569ef3495ec
    patches:
    - patches/0001-Remove-duplicate-symbol.patch
    - patches/0002-Set-fortran-linker-to-emcc.patch
    - patches/0003-Disable-threads.patch
    - patches/0004-Replace-dtype-with-numpy-int32.patch

build:
  number: 0

requirements:
  build:
    - python
    - cross-python_${{ target_platform }}
    - cython
    # we need gcc and gfortran for the preprocessor!
    - gcc_impl_linux-64
    - llvm_${{ target_platform }}
    - pip
    - numpy
    - pybind11
    - setuptools
    - meson-python
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - pkg-config

  host:
    - openblas-flang
    - python
    - pybind11
    - numpy
    - pip
    - libflang
  run:
    - python
    - numpy

tests:
- script: pytester
  requirements:
    build:
    - pytester
    - playwright == 1.50.0
    run:
    - pytester-run
    - openblas
  files:
    recipe:
    - test_scipy.py

about:
  homepage: http://www.scipy.org/
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: Scientific Library for Python
  description: |
    SciPy is a Python-based ecosystem of open-source software for mathematics,
    science, and engineering.


